[package]
name = "firebae-cm"
version = "0.1.0"
edition = "2021"

description = "A Firebase Cloud Messaging Http V1 implementation"
license = "MIT"
homepage = "https://github.com/Vesafary/firebae-cm"
repository = "https://github.com/Vesafary/firebae-cm"

[dependencies]
serde =             { version = "1.0.136", features = ["derive"] }
serde_json =        { version = "1.0.79" }
reqwest =           { version = "0.11.9", features = ["json"], default-features=false }
chrono =            { version = "0.4.19" }
log =               { version = "0.4.14" }
thiserror =         { version = "1.0.30" }
