[package]
name = "managed_oauth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
firebae-cm = { path = "../../", features = ["oauth"] }
tokio = { version = "1.26.0", features = ["full"] }